/// Built-in template for architecture summary
pub const ARCHITECTURE_TEMPLATE: &str = r#"# {{ project.root | split(pat="/") | last | default(value="Project") }} - Architecture Overview

**Generated:** {{ generated_at }}
**Files Indexed:** {{ stats.total_files }}
**Total Lines:** {{ stats.total_lines }}

## Language Breakdown

{% for lang, count in stats.language_breakdown %}| {{ lang }} | {{ count }} files |
{% endfor %}

## System Structure

```
{{ project.root | split(pat="/") | last | default(value="Project") }}/
{% for module in project.modules %}├── {{ module.name }}/{% if module.description %}          ({{ module.description }}){% endif %}
{% for subdir in module.subdirs %}│   ├── {{ subdir }}/
{% endfor %}{% endfor %}```

## Modules Overview

{% for module in project.modules %}
### {{ module.name }}

- **Path:** `{{ module.path }}`
- **Files:** {{ module.files | length }}
- **Subdirectories:** {{ module.subdirs | length }}
{% if module.description %}- **Description:** {{ module.description }}{% endif %}

{% endfor %}

## Statistics

- **Total Files:** {{ stats.total_files }}
- **Total Lines:** {{ stats.total_lines }}
- **Average File Size:** {{ stats.avg_file_size_lines | round(precision=1) }} lines
- **Modules:** {{ stats.module_count }}
{% if stats.largest_file %}
- **Largest File:** `{{ stats.largest_file.path }}` ({{ stats.largest_file.lines }} lines)
{% endif %}{% if stats.smallest_file %}
- **Smallest File:** `{{ stats.smallest_file.path }}` ({{ stats.smallest_file.lines }} lines)
{% endif %}

---
*Generated by code-summarizer*
"#;

/// Built-in template for module summary
pub const MODULE_TEMPLATE: &str = r#"# {{ module.name }} - Module Summary

**Generated:** {{ generated_at }}
**Path:** `{{ module.path }}`

## Overview

{% if module.description %}{{ module.description }}{% else %}Module containing {{ module.files | length }} files.{% endif %}

## Files

| File | Lines | Language |
|------|-------|----------|
{% for file in module.files %}| `{{ file.relative_path }}` | {{ file.lines }} | {{ file.language }} |
{% endfor %}

## Subdirectories

{% if module.subdirs | length > 0 %}{% for subdir in module.subdirs %}- `{{ subdir }}/`
{% endfor %}{% else %}No subdirectories.{% endif %}

{% if hotspots | length > 0 %}
## Hot Files in This Module

{% for hotspot in hotspots %}
### {{ hotspot.relative_path }}
- Lines: {{ hotspot.lines_of_code }}
- Changes: {{ hotspot.change_count }}
- Hotness: {{ hotspot.hotness_score | round(precision=1) }}
{% endfor %}
{% endif %}

---
*Generated by code-summarizer*
"#;

/// Built-in template for dependency graph
pub const DEPENDENCIES_TEMPLATE: &str = r#"# Dependency Graph

**Generated:** {{ generated_at }}

## Summary

- **Nodes (Files):** {{ graph.nodes | length }}
- **Edges (Dependencies):** {{ graph.edges | length }}
- **Internal Dependencies:** {{ graph.internal_count }}
- **External Dependencies:** {{ graph.external_count }}

{% if graph.cycles | length > 0 %}
## Circular Dependencies ({{ graph.cycles | length }} found)

{% for cycle in graph.cycles %}
### Cycle {{ loop.index }}
```
{% for node in cycle %}{{ node | split(pat="/") | last }}{% if not loop.last %} -> {% endif %}{% endfor %}
```
{% endfor %}
{% endif %}

## Dependency List

{% for edge in graph.edges %}
- `{{ edge.source | split(pat="/") | last }}` → `{{ edge.target | split(pat="/") | last }}` ({{ edge.dep_type }})
{% endfor %}

{% if graph.edges | length == 0 %}
No dependencies detected. This could mean:
- The project has no inter-file dependencies
- code-index hasn't indexed the project yet
- The project uses dynamic imports not tracked by static analysis
{% endif %}

---
*Generated by code-summarizer*
"#;

/// Built-in template for hotspots summary
pub const HOTSPOTS_TEMPLATE: &str = r#"# Code Hotspots

**Generated:** {{ generated_at }}
**Showing:** {{ hotspots | length }} of {{ total_count }} files

## What are Hotspots?

Hotspots are files that combine multiple risk factors:
- **Lines of Code:** Larger files are harder to maintain
- **Change Frequency:** Frequently modified files may be unstable
- **Dependencies:** Files with many dependencies are more coupled

The **hotness score** combines these factors to identify files that may need attention.

## Top Hotspots

{% for hotspot in hotspots %}
### {{ loop.index }}. {{ hotspot.relative_path }}

| Metric | Value |
|--------|-------|
| Lines of Code | {{ hotspot.lines_of_code }} |
| Change Count | {{ hotspot.change_count }} |
| Dependencies | {{ hotspot.dependency_count }} |
| Complexity Score | {{ hotspot.complexity_score | round(precision=1) }} |
| **Hotness Score** | **{{ hotspot.hotness_score | round(precision=1) }}** |

{% endfor %}

{% if hotspots | length == 0 %}
No hotspots detected. This could mean:
- The project is well-maintained with evenly distributed complexity
- Not enough git history to calculate change frequency
- code-index hasn't indexed the project yet
{% endif %}

## Hotness Formula

```
hotness = (change_count × 2.0) + (lines / 100.0) + (dependencies × 1.5)
```

Higher scores indicate files that may benefit from:
- Refactoring to reduce complexity
- Breaking into smaller modules
- Additional testing
- Code review focus

---
*Generated by code-summarizer*
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_architecture_template_valid_tera() {
        let mut tera = tera::Tera::default();
        let result = tera.add_raw_template("test", ARCHITECTURE_TEMPLATE);
        assert!(result.is_ok(), "Architecture template is invalid: {:?}", result.err());
    }

    #[test]
    fn test_module_template_valid_tera() {
        let mut tera = tera::Tera::default();
        let result = tera.add_raw_template("test", MODULE_TEMPLATE);
        assert!(result.is_ok(), "Module template is invalid: {:?}", result.err());
    }

    #[test]
    fn test_dependencies_template_valid_tera() {
        let mut tera = tera::Tera::default();
        let result = tera.add_raw_template("test", DEPENDENCIES_TEMPLATE);
        assert!(result.is_ok(), "Dependencies template is invalid: {:?}", result.err());
    }

    #[test]
    fn test_hotspots_template_valid_tera() {
        let mut tera = tera::Tera::default();
        let result = tera.add_raw_template("test", HOTSPOTS_TEMPLATE);
        assert!(result.is_ok(), "Hotspots template is invalid: {:?}", result.err());
    }

    #[test]
    fn test_architecture_template_contains_key_sections() {
        assert!(ARCHITECTURE_TEMPLATE.contains("Architecture Overview"));
        assert!(ARCHITECTURE_TEMPLATE.contains("Language Breakdown"));
        assert!(ARCHITECTURE_TEMPLATE.contains("System Structure"));
        assert!(ARCHITECTURE_TEMPLATE.contains("Modules Overview"));
        assert!(ARCHITECTURE_TEMPLATE.contains("Statistics"));
    }

    #[test]
    fn test_module_template_contains_key_sections() {
        assert!(MODULE_TEMPLATE.contains("Module Summary"));
        assert!(MODULE_TEMPLATE.contains("Files"));
        assert!(MODULE_TEMPLATE.contains("Subdirectories"));
    }

    #[test]
    fn test_dependencies_template_contains_key_sections() {
        assert!(DEPENDENCIES_TEMPLATE.contains("Dependency Graph"));
        assert!(DEPENDENCIES_TEMPLATE.contains("Circular Dependencies"));
        assert!(DEPENDENCIES_TEMPLATE.contains("Dependency List"));
    }

    #[test]
    fn test_hotspots_template_contains_key_sections() {
        assert!(HOTSPOTS_TEMPLATE.contains("Code Hotspots"));
        assert!(HOTSPOTS_TEMPLATE.contains("What are Hotspots"));
        assert!(HOTSPOTS_TEMPLATE.contains("Top Hotspots"));
        assert!(HOTSPOTS_TEMPLATE.contains("Hotness Formula"));
    }
}
