/// Built-in template for architecture summary
pub const ARCHITECTURE_TEMPLATE: &str = r#"# {{ project.root | split(pat="/") | last | default(value="Project") }} - Architecture Overview

**Generated:** {{ generated_at }}
**Files Indexed:** {{ stats.total_files }}
**Total Lines:** {{ stats.total_lines }}

## Language Breakdown

{% for lang, count in stats.language_breakdown %}| {{ lang }} | {{ count }} files |
{% endfor %}

## System Structure

```
{{ project.root | split(pat="/") | last | default(value="Project") }}/
{% for module in project.modules %}├── {{ module.name }}/{% if module.description %}          ({{ module.description }}){% endif %}
{% for subdir in module.subdirs %}│   ├── {{ subdir }}/
{% endfor %}{% endfor %}```

{% if project.entry_points | length > 0 %}
## Entry Points

{% for entry in project.entry_points %}
### {% if entry.kind == "MainFunction" %}CLI Entry{% elif entry.kind == "LibraryRoot" %}Library Root{% elif entry.kind == "ModuleRoot" %}Module Root{% else %}Entry{% endif %}: `{{ entry.file_path }}`
{% if entry.exports | length > 0 %}
**Exports:** {{ entry.exports | join(sep=", ") }}
{% endif %}
{% endfor %}
{% endif %}

## Modules Overview

{% for module in project.modules %}
### {{ module.name }}

- **Path:** `{{ module.path }}`
- **Files:** {{ module.files | length }}
{% if module.purpose %}
- **Purpose:** {{ module.purpose.summary }}
{% if module.purpose.patterns | length > 0 %}- **Patterns:** {{ module.purpose.patterns | join(sep=", ") }}{% endif %}
{% if module.purpose.key_components | length > 0 %}- **Key Components:** {{ module.purpose.key_components | join(sep=", ") }}{% endif %}
{% endif %}

{% if module.public_apis | length > 0 %}
#### Public API ({{ module.public_apis | length }} items)
{% for api in module.public_apis | slice(end=5) %}
- `{{ api.signature | truncate(length=80) }}`
{% endfor %}
{% set api_count = module.public_apis | length %}
{% if api_count > 5 %}
*... and {{ api_count - 5 }} more*
{% endif %}
{% endif %}

{% if module.traits | length > 0 %}
#### Traits Defined
{% for trait in module.traits %}
- **{{ trait.name }}** ({{ trait.methods | length }} methods)
{% endfor %}
{% endif %}

{% endfor %}

{% if project.all_traits | length > 0 %}
## Trait Implementations

{% for impl in project.all_trait_impls %}
- `{{ impl.impl_type }}` implements `{{ impl.trait_name }}` (`{{ impl.file_path }}:{{ impl.line }}`)
{% endfor %}
{% endif %}

## Statistics

- **Total Files:** {{ stats.total_files }}
- **Total Lines:** {{ stats.total_lines }}
- **Average File Size:** {{ stats.avg_file_size_lines | round(precision=1) }} lines
- **Modules:** {{ stats.module_count }}
{% if stats.largest_file %}
- **Largest File:** `{{ stats.largest_file.path }}` ({{ stats.largest_file.lines }} lines)
{% endif %}{% if stats.smallest_file %}
- **Smallest File:** `{{ stats.smallest_file.path }}` ({{ stats.smallest_file.lines }} lines)
{% endif %}

---
*Generated by code-summarizer*
"#;

/// Built-in template for module summary
pub const MODULE_TEMPLATE: &str = r#"# {{ module.name }} - Module Summary

**Generated:** {{ generated_at }}
**Path:** `{{ module.path }}`

## Overview

{% if module.purpose %}
**Purpose:** {{ module.purpose.summary }}
{% if module.purpose.patterns | length > 0 %}

**Patterns:** {{ module.purpose.patterns | join(sep=", ") }}
{% endif %}
{% if module.purpose.key_components | length > 0 %}

**Key Components:** {{ module.purpose.key_components | join(sep=", ") }}
{% endif %}
{% else %}
Module containing {{ module.files | length }} files.
{% endif %}

{% if module.public_apis | length > 0 %}
## Public API

{% for api in module.public_apis %}
### {{ api.name }} ({{ api.kind }})

```
{{ api.signature }}
```
{% if api.doc_comment %}
{{ api.doc_comment }}
{% endif %}

*Location: `{{ api.file_path }}:{{ api.line }}`*

{% endfor %}
{% endif %}

{% if module.traits | length > 0 %}
## Traits Defined

{% for trait in module.traits %}
### {{ trait.name }}

{% if trait.doc_comment %}{{ trait.doc_comment }}{% endif %}

**Methods:**
{% for method in trait.methods %}
- `{{ method.signature }}`
{% endfor %}

*Location: `{{ trait.file_path }}:{{ trait.line }}`*

{% endfor %}
{% endif %}

{% if module.types | length > 0 %}
## Type Definitions

{% for type in module.types %}
### {{ type.name }} ({{ type.kind }})

{% if type.fields | length > 0 %}
**Fields:**
{% for field in type.fields %}
- `{{ field.name }}`: {{ field.type_annotation }}
{% endfor %}
{% endif %}

{% if type.methods | length > 0 %}
**Methods:**
{% for method in type.methods %}
- `{{ method.signature }}`
{% endfor %}
{% endif %}

*Location: `{{ type.file_path }}:{{ type.line }}`*

{% endfor %}
{% endif %}

## Files

| File | Lines | Language |
|------|-------|----------|
{% for file in module.files %}| `{{ file.relative_path }}` | {{ file.lines }} | {{ file.language }} |
{% endfor %}

## Subdirectories

{% if module.subdirs | length > 0 %}{% for subdir in module.subdirs %}- `{{ subdir }}/`
{% endfor %}{% else %}No subdirectories.{% endif %}

{% if hotspots | length > 0 %}
## Hot Files in This Module

{% for hotspot in hotspots %}
### {{ hotspot.relative_path }}
- Lines: {{ hotspot.lines_of_code }}
- Changes: {{ hotspot.change_count }}
- Hotness: {{ hotspot.hotness_score | round(precision=1) }}
{% endfor %}
{% endif %}

---
*Generated by code-summarizer*
"#;

/// Built-in template for dependency graph
pub const DEPENDENCIES_TEMPLATE: &str = r#"# Dependency Graph

**Generated:** {{ generated_at }}

## Summary

- **Nodes (Files):** {{ graph.nodes | length }}
- **Edges (Dependencies):** {{ graph.edges | length }}
- **Internal Dependencies:** {{ graph.internal_count }}
- **External Dependencies:** {{ graph.external_count }}

{% if graph.cycles | length > 0 %}
## Circular Dependencies ({{ graph.cycles | length }} found)

{% for cycle in graph.cycles %}
### Cycle {{ loop.index }}
```
{% for node in cycle %}{{ node | split(pat="/") | last }}{% if not loop.last %} -> {% endif %}{% endfor %}
```
{% endfor %}
{% endif %}

## Dependency List

{% for edge in graph.edges %}
- `{{ edge.source | split(pat="/") | last }}` → `{{ edge.target | split(pat="/") | last }}` ({{ edge.dep_type }})
{% endfor %}

{% if graph.edges | length == 0 %}
No dependencies detected. This could mean:
- The project has no inter-file dependencies
- code-index hasn't indexed the project yet
- The project uses dynamic imports not tracked by static analysis
{% endif %}

---
*Generated by code-summarizer*
"#;

/// Built-in template for hotspots summary
pub const HOTSPOTS_TEMPLATE: &str = r#"# Code Hotspots

**Generated:** {{ generated_at }}
**Showing:** {{ hotspots | length }} of {{ total_count }} files

## What are Hotspots?

Hotspots are files that combine multiple risk factors:
- **Lines of Code:** Larger files are harder to maintain
- **Change Frequency:** Frequently modified files may be unstable
- **Dependencies:** Files with many dependencies are more coupled
- **Cyclomatic Complexity:** Files with many branches are harder to test
- **Nesting Depth:** Deeply nested code is harder to understand

The **hotness score** combines these factors to identify files that may need attention.

## Top Hotspots

{% for hotspot in hotspots %}
### {{ loop.index }}. {{ hotspot.relative_path }}{% if hotspot.enhanced_metrics %} - {{ hotspot.enhanced_metrics.priority }} PRIORITY{% endif %}

| Metric | Value |{% if hotspot.enhanced_metrics %} Concern |{% endif %}
|--------|-------|{% if hotspot.enhanced_metrics %}---------|{% endif %}
| Lines of Code | {{ hotspot.lines_of_code }} |{% if hotspot.enhanced_metrics %}{% if hotspot.lines_of_code > 300 %} Large file |{% else %} OK |{% endif %}{% endif %}
| Change Count | {{ hotspot.change_count }} |{% if hotspot.enhanced_metrics %}{% if hotspot.change_count > 15 %} Frequently changed |{% else %} OK |{% endif %}{% endif %}
| Dependencies | {{ hotspot.dependency_count }} |{% if hotspot.enhanced_metrics %}{% if hotspot.dependency_count > 8 %} High coupling |{% else %} OK |{% endif %}{% endif %}
{% if hotspot.enhanced_metrics %}| Cyclomatic Complexity | {{ hotspot.enhanced_metrics.cyclomatic_complexity }} |{% if hotspot.enhanced_metrics.cyclomatic_complexity > 15 %} High branching |{% else %} OK |{% endif %}
| Nesting Depth (max) | {{ hotspot.enhanced_metrics.max_nesting_depth }} |{% if hotspot.enhanced_metrics.max_nesting_depth > 4 %} Deep nesting |{% else %} OK |{% endif %}
| Public API Surface | {{ hotspot.enhanced_metrics.public_api_surface }} |{% if hotspot.enhanced_metrics.public_api_surface > 10 %} Large interface |{% else %} OK |{% endif %}
| Function Count | {{ hotspot.enhanced_metrics.function_count }} |
{% endif %}| Complexity Score | {{ hotspot.complexity_score | round(precision=1) }} |
| **Hotness Score** | **{{ hotspot.hotness_score | round(precision=1) }}** |

{% if hotspot.enhanced_metrics and hotspot.enhanced_metrics.recommendations | length > 0 %}
**Recommendations:**
{% for rec in hotspot.enhanced_metrics.recommendations %}
- {{ rec }}
{% endfor %}
{% endif %}

{% endfor %}

{% if hotspots | length == 0 %}
No hotspots detected. This could mean:
- The project is well-maintained with evenly distributed complexity
- Not enough git history to calculate change frequency
- code-index hasn't indexed the project yet
{% endif %}

## Hotness Formula

```
hotness = (change_count × 2.0) + (lines / 100.0) + (dependencies × 1.5)
         + (cyclomatic_complexity × 0.8) + (public_api_surface × 0.3)
```

Higher scores indicate files that may benefit from:
- Refactoring to reduce complexity
- Breaking into smaller modules
- Additional testing
- Code review focus

---
*Generated by code-summarizer*
"#;

/// Built-in template for public API reference
pub const API_TEMPLATE: &str = r#"# Public API Reference

**Generated:** {{ generated_at }}

This document provides a comprehensive reference of all public APIs in the codebase.

{% for module in modules %}
## {{ module.name }}

{% if module.purpose %}
*{{ module.purpose.summary }}*
{% endif %}

{% if module.traits | length > 0 %}
### Traits

{% for trait in module.traits %}
#### {{ trait.name }}

```
trait {{ trait.name }} {
{% for method in trait.methods %}    {{ method.signature }};
{% endfor %}}
```

{% if trait.doc_comment %}
{{ trait.doc_comment }}
{% endif %}

*Defined in `{{ trait.file_path }}:{{ trait.line }}`*

{% endfor %}
{% endif %}

{% if module.types | length > 0 %}
### Types

{% for type in module.types %}
#### {{ type.name }} ({{ type.kind }})

{% if type.fields | length > 0 %}
**Fields:**
| Name | Type |
|------|------|
{% for field in type.fields %}| `{{ field.name }}` | `{{ field.type_annotation }}` |
{% endfor %}
{% endif %}

{% if type.methods | length > 0 %}
**Methods:**
{% for method in type.methods %}
- `{{ method.signature }}`
{% endfor %}
{% endif %}

*Defined in `{{ type.file_path }}:{{ type.line }}`*

{% endfor %}
{% endif %}

{% if module.public_apis | length > 0 %}
### Functions

{% for api in module.public_apis %}
{% if api.kind == "Function" %}
#### `{{ api.name }}`

```
{{ api.signature }}
```

{% if api.doc_comment %}
{{ api.doc_comment }}
{% endif %}

*Defined in `{{ api.file_path }}:{{ api.line }}`*

{% endif %}
{% endfor %}
{% endif %}

{% endfor %}

---
*Generated by code-summarizer*
"#;

/// Built-in template for type definitions
pub const TYPES_TEMPLATE: &str = r#"# Core Type Definitions

**Generated:** {{ generated_at }}

This document lists all public types (structs, enums, classes) defined in the codebase.

{% for module in modules %}
{% if module.types | length > 0 %}
## {{ module.name }}

{% for type in module.types %}
### {{ type.name }}

```
{% if type.kind == "Struct" %}pub struct {{ type.name }} {
{% for field in type.fields %}    pub {{ field.name }}: {{ field.type_annotation }},
{% endfor %}}{% elif type.kind == "Enum" %}pub enum {{ type.name }} {
{% for field in type.fields %}    {{ field.name }},
{% endfor %}}{% else %}{{ type.kind }} {{ type.name }} { ... }{% endif %}
```

{% if type.doc_comment %}
{{ type.doc_comment }}
{% endif %}

{% if type.methods | length > 0 %}
**Methods:**
{% for method in type.methods %}
- `{{ method.signature }}`
{% endfor %}
{% endif %}

*Location: `{{ type.file_path }}:{{ type.line }}`*

{% endfor %}
{% endif %}
{% endfor %}

---
*Generated by code-summarizer*
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_architecture_template_valid_tera() {
        let mut tera = tera::Tera::default();
        let result = tera.add_raw_template("test", ARCHITECTURE_TEMPLATE);
        assert!(result.is_ok(), "Architecture template is invalid: {:?}", result.err());
    }

    #[test]
    fn test_module_template_valid_tera() {
        let mut tera = tera::Tera::default();
        let result = tera.add_raw_template("test", MODULE_TEMPLATE);
        assert!(result.is_ok(), "Module template is invalid: {:?}", result.err());
    }

    #[test]
    fn test_dependencies_template_valid_tera() {
        let mut tera = tera::Tera::default();
        let result = tera.add_raw_template("test", DEPENDENCIES_TEMPLATE);
        assert!(result.is_ok(), "Dependencies template is invalid: {:?}", result.err());
    }

    #[test]
    fn test_hotspots_template_valid_tera() {
        let mut tera = tera::Tera::default();
        let result = tera.add_raw_template("test", HOTSPOTS_TEMPLATE);
        assert!(result.is_ok(), "Hotspots template is invalid: {:?}", result.err());
    }

    #[test]
    fn test_architecture_template_contains_key_sections() {
        assert!(ARCHITECTURE_TEMPLATE.contains("Architecture Overview"));
        assert!(ARCHITECTURE_TEMPLATE.contains("Language Breakdown"));
        assert!(ARCHITECTURE_TEMPLATE.contains("System Structure"));
        assert!(ARCHITECTURE_TEMPLATE.contains("Modules Overview"));
        assert!(ARCHITECTURE_TEMPLATE.contains("Statistics"));
    }

    #[test]
    fn test_module_template_contains_key_sections() {
        assert!(MODULE_TEMPLATE.contains("Module Summary"));
        assert!(MODULE_TEMPLATE.contains("Files"));
        assert!(MODULE_TEMPLATE.contains("Subdirectories"));
    }

    #[test]
    fn test_dependencies_template_contains_key_sections() {
        assert!(DEPENDENCIES_TEMPLATE.contains("Dependency Graph"));
        assert!(DEPENDENCIES_TEMPLATE.contains("Circular Dependencies"));
        assert!(DEPENDENCIES_TEMPLATE.contains("Dependency List"));
    }

    #[test]
    fn test_hotspots_template_contains_key_sections() {
        assert!(HOTSPOTS_TEMPLATE.contains("Code Hotspots"));
        assert!(HOTSPOTS_TEMPLATE.contains("What are Hotspots"));
        assert!(HOTSPOTS_TEMPLATE.contains("Top Hotspots"));
        assert!(HOTSPOTS_TEMPLATE.contains("Hotness Formula"));
    }
}
