mod renderer;
mod builtin;

pub use renderer::*;

use anyhow::Result;
use std::path::Path;

/// List all available templates
pub fn list_templates() -> Result<()> {
    println!("Available Templates:");
    println!("====================\n");

    println!("Built-in Templates:");
    println!("  - architecture    High-level system overview");
    println!("  - module          Per-module breakdown");
    println!("  - dependencies    Dependency graph visualization");
    println!("  - hotspots        Complex/risky file analysis");

    // Check for custom templates
    let custom_dir = dirs::config_dir()
        .map(|p| p.join("ai-tools/templates"))
        .unwrap_or_default();

    if custom_dir.exists() {
        println!("\nCustom Templates ({:?}):", custom_dir);
        for entry in std::fs::read_dir(&custom_dir)? {
            let entry = entry?;
            let name = entry.file_name().to_string_lossy().to_string();
            if name.ends_with(".tera") || name.ends_with(".md.tera") {
                println!("  - {}", name);
            }
        }
    } else {
        println!("\nNo custom templates found.");
        println!("Create custom templates in: {:?}", custom_dir);
    }

    Ok(())
}

/// Create a new template
pub fn create_template(name: &str) -> Result<()> {
    let custom_dir = dirs::config_dir()
        .map(|p| p.join("ai-tools/templates"))
        .ok_or_else(|| anyhow::anyhow!("Could not determine config directory"))?;

    std::fs::create_dir_all(&custom_dir)?;

    let template_path = custom_dir.join(format!("{}.md.tera", name));

    if template_path.exists() {
        anyhow::bail!("Template '{}' already exists at {:?}", name, template_path);
    }

    let template_content = r#"# {{ project.name | default(value="Project") }} - {{ title }}

**Generated:** {{ generated_at }}
**Files:** {{ project.total_files | default(value=0) }}

## Overview

{# Add your custom template content here #}
{% for module in project.modules %}
### {{ module.name }}
- Files: {{ module.files | length }}
- Path: {{ module.path }}
{% endfor %}

---
*Generated by code-summarizer*
"#;

    std::fs::write(&template_path, template_content)?;
    println!("Created template: {:?}", template_path);

    Ok(())
}

/// Validate a template file
pub fn validate_template(file: &Path) -> Result<()> {
    if !file.exists() {
        anyhow::bail!("Template file not found: {:?}", file);
    }

    let content = std::fs::read_to_string(file)?;

    // Try to parse with Tera
    let mut tera = tera::Tera::default();
    match tera.add_raw_template("validate", &content) {
        Ok(_) => {
            println!("Template is valid: {:?}", file);
            Ok(())
        }
        Err(e) => {
            println!("Template validation failed: {:?}", file);
            println!("Error: {}", e);
            Err(e.into())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_validate_template_valid() {
        let temp = TempDir::new().unwrap();
        let template_path = temp.path().join("test.md.tera");

        std::fs::write(&template_path, "# {{ title }}\n{{ content }}").unwrap();

        let result = validate_template(&template_path);
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_template_invalid() {
        let temp = TempDir::new().unwrap();
        let template_path = temp.path().join("test.md.tera");

        // Invalid Tera syntax - unclosed tag
        std::fs::write(&template_path, "# {{ title }\n").unwrap();

        let result = validate_template(&template_path);
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_template_not_found() {
        let result = validate_template(Path::new("/nonexistent/template.tera"));
        assert!(result.is_err());
    }
}
